import {tmpdir} from 'node:os';
import {join} from 'node:path';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {writeFileSync} from 'node:fs';
import {definitions} from '../dist/modules/components.js';
import {Store,demoDiagram,blankDiagram,createNode,clone,transposeOrientation} from '../dist/modules/model.js';
import {validate,modelErrors} from '../dist/modules/validation.js';
import {toXML,fromXML} from '../dist/modules/io.js';
import {edgePoints,port,exportSVG} from '../dist/modules/canvas.js';
const require=createRequire(import.meta.url);
// A Node-only XML adapter; this does not constitute browser UI validation.
const xmljs=require(require.resolve('xml-js',{paths:[process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES||process.cwd()]}));
const wrap=e=>({tagName:e.name,children:(e.elements||[]).filter(x=>x.type==='element').map(wrap),get textContent(){return(e.elements||[]).map(x=>x.type==='element'?wrap(x).textContent:x.text||x.cdata||'').join('');},getAttribute:k=>e.attributes?.[k]??null,hasAttribute:k=>Object.hasOwn(e.attributes||{},k)});
globalThis.DOMParser=class{parseFromString(xml){try{const parsed=xmljs.xml2js(xml);return {documentElement:wrap(parsed.elements.find(e=>e.type==='element')),querySelector:()=>null};}catch{return{querySelector:()=>({})};}}};
globalThis.localStorage={setItem(){}};
const d=demoDiagram();
assert.equal(Object.keys(definitions).length,73);
assert.deepEqual(modelErrors(d),[]);
assert.equal(validate(d).errors,0);
assert.equal(validate(d).warnings,0);
assert.deepEqual(fromXML(toXML(d)),d,'XML preserves the entire project');
const special=clone(d);special.name='API <process> & "review"';special.nodes[0].properties.notes='Line 1\nLine 2 & <check>';special.metadata={owner:'A & B',nested:{references:['x','y']}};special.nodes[0].properties.additional={'A & B':'α × ρ'};assert.deepEqual(fromXML(toXML(special)),special,'XML safely preserves text and custom metadata');
const original=clone(d);transposeOrientation(d,'vertical');assert.equal(d.settings.orientation,'vertical');assert.deepEqual(modelErrors(d),[]);transposeOrientation(d,'horizontal');assert.deepEqual(d,original,'Orientation is fully reversible');
for(const edge of d.edges){const points=edgePoints(edge,d.nodes);assert.deepEqual(points[0],port(d.nodes.find(n=>n.id===edge.source),edge.sourcePort));assert.deepEqual(points.at(-1),port(d.nodes.find(n=>n.id===edge.destination),edge.destinationPort));for(let i=1;i<points.length;i++)assert.ok(points[i].x===points[i-1].x||points[i].y===points[i-1].y,'Every routing segment is orthogonal');}
const moved=clone(d);moved.nodes.find(n=>n.id==='mix').x+=74;moved.nodes.find(n=>n.id==='mix').width+=63;for(const e of moved.edges.filter(e=>e.destination==='mix'))assert.deepEqual(edgePoints(e,moved.nodes).at(-1),port(moved.nodes.find(n=>n.id==='mix'),e.destinationPort),'Ports remain attached after resizing');
assert.throws(()=>fromXML(toXML(d).replace('destination="mix"','destination="missing"')),/missing source or destination/);
assert.throws(()=>fromXML(toXML(d).replace('sourcePort="right"','sourcePort="unknown"')),/incompatible port/);
assert.throws(()=>fromXML(toXML(d).replace('<tengwar version="1.0">','<tengwar version="3.0">')),/supported/);
assert.throws(()=>fromXML('<!DOCTYPE tengwar><tengwar/>'),/declarations/);
assert.throws(()=>fromXML(toXML(d).replace('type="raw-material"','type="unknown"')),/Unknown component type/);
assert.throws(()=>fromXML(toXML(d).replace('x="40"','x="NaN"')),/Invalid dimensions/);
assert.throws(()=>fromXML(toXML(d).replace('id="solvent"','id="raw"')),/duplicate ID/);
const issues=clone(d);issues.nodes.find(n=>n.id==='reaction').properties.equipmentId='F-101';issues.edges[1].properties.streamId=issues.edges[0].properties.streamId;issues.nodes.find(n=>n.id==='qc').properties.reference='';const findings=validate(issues).findings;assert.ok(findings.some(f=>f.message.includes('Duplicate Equipment')));assert.ok(findings.some(f=>f.message.includes('Duplicate Stream')));assert.ok(findings.some(f=>f.check==='QC references'));
const cycle=clone(d);cycle.edges.filter(e=>e.properties.type==='Recycle').forEach(e=>{e.properties.type='Process';e.properties.linkType='Main Process Flow';});assert.ok(validate(cycle).findings.some(f=>f.check==='Recycle loops'));
const empty=blankDiagram();empty.nodes.push(createNode('split',0,0));assert.ok(validate(empty).findings.some(f=>f.check==='Split outputs'));
const history=new Store(clone(d));history.commit(x=>x.nodes.splice(0,1));assert.equal(history.diagram.nodes.length,14);assert.ok(history.undo());assert.deepEqual(history.diagram,d);assert.ok(history.redo());assert.equal(history.diagram.nodes.length,14);history.undo();history.commit(x=>x.name='New name');assert.equal(history.future.length,0);
const svg=exportSVG(d);assert.ok(!svg.includes('class="port"'));assert.ok(!svg.includes('route-handle'));assert.ok(svg.includes('marker-end'));const transparent=exportSVG(d,true);assert.ok(transparent.length<svg.length);assert.ok(!transparent.includes('<rect x="-5" y="-15" width="'));xmljs.xml2js(svg);xmljs.xml2js(transparent);
writeFileSync(join(tmpdir(), 'tengwar-demo.svg'),svg);
writeFileSync(join(tmpdir(), 'tengwar-demo.xml'),toXML(d));
console.log('PASS: 73 component definitions, exact XML round-trip, malformed file rejection, reversible orientation, anchored orthogonal routing, structural findings, undo/redo and SVG export.');
