// Reuse the Node-only XML adapter and core regression checks.
import './core.test.mjs';
import assert from 'node:assert/strict';
import {Store,blankProject,blankDiagram,demoDiagram,asProject,clone,uid} from '../dist/modules/model.js';
import {projectErrors} from '../dist/modules/validation.js';
import {toXML,fromXML} from '../dist/modules/io.js';
let saved;
globalThis.localStorage={setItem(key,value){assert.equal(key,'tengwar.project.v2');saved=JSON.parse(value);}};
const project=blankProject('API development');
assert.equal(project.diagrams.length,1);
assert.equal(project.diagrams[0].nodes.length,0,'A new project starts empty');
assert.equal(project.diagrams[0].name,'Flow 1');
const store=new Store(project);const first=store.diagram.id;
store.commit(d=>{d.name='Preparation';d.description='Independent process flow';d.metadata={SOP:'SOP-100'};});
const example=demoDiagram();store.addFlow(example);const second=store.diagram.id;
assert.equal(store.project.diagrams.length,2);assert.equal(store.diagram.nodes.length,15);
store.commit(d=>{d.settings.theme='dark';d.nodes[0].properties.additional={batch:'2026-09'};});
store.switchFlow(first);assert.equal(store.diagram.nodes.length,0);assert.equal(store.diagram.settings.theme,'light');assert.equal(store.diagram.metadata.SOP,'SOP-100');
store.switchFlow(second);assert.equal(store.diagram.settings.theme,'dark');
store.project.metadata={folder:'Development & scale-up',nested:{references:['R&D','SOP-100']}};
const xml=toXML(store.project);assert.ok(xml.includes('<tengwar version="2.0">'));assert.equal((xml.match(/<diagram /g)||[]).length,2);
assert.deepEqual(fromXML(xml),store.project,'One XML restores all flows, metadata, tab order and active flow');
assert.deepEqual(projectErrors(fromXML(xml)),[]);
const copiedId=store.duplicateFlow(second);assert.notEqual(copiedId,second);assert.deepEqual(store.diagram.nodes,example.nodes,'Duplicating a flow preserves scoped node IDs and connections');
store.commit(d=>d.nodes[0].properties.name='Independent copy');assert.notEqual(store.project.diagrams.find(d=>d.id===second).nodes[0].properties.name,'Independent copy','Copies do not share mutable state');
const beforeDelete=clone(store.project);store.deleteFlow(copiedId);assert.equal(store.project.diagrams.length,2);assert.ok(store.undo());assert.deepEqual(store.project,beforeDelete,'Undo restores a deleted tab and its whole flow');assert.ok(store.redo());assert.equal(store.project.diagrams.length,2);
const beforeFail=clone(store.project);assert.throws(()=>store.commit((d,p)=>{d.name='broken';p.name='broken';throw Error('Abort');}),/Abort/);assert.deepEqual(store.project,beforeFail,'Failed project changes roll back atomically');
const beforeImport=clone(store.project);const corrupt=toXML(store.project).replace('destination="mix"','destination="not-in-this-flow"');assert.throws(()=>store.replace(asProject(fromXML(corrupt))),/missing source or destination/);assert.deepEqual(store.project,beforeImport,'Bad inactive flows cannot partially overwrite a project');
assert.throws(()=>fromXML(toXML(store.project).replace('activeDiagramId="'+store.project.activeDiagramId+'"','activeDiagramId="missing"')),/active flow/);
const bad=clone(store.project);bad.diagrams[1].id=bad.diagrams[0].id;assert.ok(projectErrors(bad).some(e=>e.includes('Duplicate flow')));
const legacy=demoDiagram(),migrated=asProject(fromXML(toXML(legacy)));assert.equal(migrated.diagrams.length,1);assert.deepEqual(migrated.diagrams[0],legacy,'Legacy XML imports without altering geometry or properties');
store.persist();assert.deepEqual(saved,store.project,'Local recovery retains every flow');
const single=new Store(blankProject());assert.throws(()=>single.deleteFlow(single.diagram.id),/at least one/);assert.equal(single.project.diagrams.length,1);
const extra=blankDiagram();extra.id=single.diagram.id;assert.throws(()=>single.addFlow(extra),/Duplicate flow ID/);
console.log('PASS: blank startup, independent tabs, project XML round-trip, legacy compatibility, duplicate/delete/undo, atomic import and local project recovery.');
